#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
Run Qwen3-4B on a few AIME problems and dump (prompt + chain-of-thought
response) sequences usable as a prefill workload for the kernel-level
MoE benchmark.

The output is a JSONL where each line has::

    {
        "problem_id": int,
        "answer": str,
        "user_prompt":  "<the problem text>",
        "model_response": "<text generated by Qwen3-4B>",
        "full_text":   "<chat-templated user turn followed by model turn>"
    }

A companion ``.txt`` file is also written: it concatenates the
``full_text`` fields with double-newline separators, suitable to pass to
``capture_routing_trace.py --prompt-file``.

The point of this script is **not** to evaluate Qwen3-4B's math ability;
it is to manufacture a realistic long, semantically-coherent prefill
workload to drive the Qwen3-30B-A3B routing capture, instead of a single
short prompt or a synthetic Gaussian stream.
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

import torch


def _load_aime(path: Path, num_problems: int, start: int = 0) -> list[dict]:
    rows: list[dict] = []
    with path.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    if not rows:
        raise RuntimeError(f"No rows in {path}")
    end = min(start + num_problems, len(rows))
    return rows[start:end]


SYSTEM_PROMPT = (
    "You are a careful math tutor solving AIME problems. Always reason step "
    "by step, show the algebra, and finish with the final integer answer in "
    "the form `Answer: <integer>` on its own line."
)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", type=str, default="/home/yyx/models/Qwen3-4B")
    parser.add_argument(
        "--aime",
        type=Path,
        default=Path("/home/yyx/personal/Artifact-Infer/datasets/aime24.json"),
        help="AIME jsonl with at least 'problem' / 'answer' fields.",
    )
    parser.add_argument("--num-problems", type=int, default=5)
    parser.add_argument("--start", type=int, default=0)
    parser.add_argument(
        "--max-new-tokens",
        type=int,
        default=512,
        help="Max tokens to generate per AIME problem.",
    )
    parser.add_argument("--temperature", type=float, default=0.7)
    parser.add_argument("--top-p", type=float, default=0.8)
    parser.add_argument("--seed", type=int, default=7)
    parser.add_argument(
        "--output-jsonl",
        type=Path,
        required=True,
        help="Where to write the per-problem JSONL.",
    )
    parser.add_argument(
        "--output-text",
        type=Path,
        default=None,
        help="Optional path to a single concatenated text file ready to "
        "feed --prompt-file.",
    )
    parser.add_argument("--dtype", choices=["bf16", "fp16"], default="bf16")
    parser.add_argument("--device-map", type=str, default="auto")
    args = parser.parse_args()

    from transformers import AutoModelForCausalLM, AutoTokenizer
    from transformers import set_seed

    set_seed(args.seed)
    torch.manual_seed(args.seed)

    print(f"[gen] loading {args.model}")
    tokenizer = AutoTokenizer.from_pretrained(args.model, trust_remote_code=True)
    dtype = {"bf16": torch.bfloat16, "fp16": torch.float16}[args.dtype]
    model = AutoModelForCausalLM.from_pretrained(
        args.model, dtype=dtype, device_map=args.device_map, trust_remote_code=True
    )
    model.eval()
    if tokenizer.pad_token_id is None:
        tokenizer.pad_token_id = tokenizer.eos_token_id

    problems = _load_aime(args.aime, args.num_problems, args.start)
    print(f"[gen] running {len(problems)} AIME problems (start={args.start})")

    args.output_jsonl.parent.mkdir(parents=True, exist_ok=True)
    if args.output_text:
        args.output_text.parent.mkdir(parents=True, exist_ok=True)

    out_rows: list[dict] = []
    cumulative_text_chunks: list[str] = []
    for i, prob in enumerate(problems):
        problem_text = prob.get("problem") or prob.get("question") or ""
        answer = str(prob.get("answer", ""))
        problem_id = prob.get("id", args.start + i)

        messages = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user",   "content": problem_text.strip()},
        ]
        prompt_text = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
        )
        enc = tokenizer(prompt_text, return_tensors="pt")
        device = model.device if hasattr(model, "device") else "cuda:0"
        input_ids = enc["input_ids"].to(device)
        attn_mask = enc["attention_mask"].to(device)

        t0 = time.time()
        with torch.no_grad():
            out = model.generate(
                input_ids=input_ids,
                attention_mask=attn_mask,
                max_new_tokens=args.max_new_tokens,
                do_sample=True,
                temperature=args.temperature,
                top_p=args.top_p,
                pad_token_id=tokenizer.pad_token_id,
                use_cache=True,
            )
        dt = time.time() - t0

        new_token_ids = out[0, input_ids.shape[-1]:]
        response_text = tokenizer.decode(
            new_token_ids, skip_special_tokens=True
        )
        full_text = tokenizer.decode(out[0], skip_special_tokens=False)
        prompt_tok = int(input_ids.shape[-1])
        gen_tok = int(new_token_ids.shape[-1])
        print(
            f"[gen] problem {i + 1}/{len(problems)} (id={problem_id}, "
            f"answer={answer}): prompt {prompt_tok} tok, "
            f"generated {gen_tok} tok in {dt:.1f}s "
            f"({gen_tok / max(dt, 1e-6):.1f} tok/s)"
        )

        row = {
            "problem_id":     problem_id,
            "answer":         answer,
            "user_prompt":    problem_text,
            "model_response": response_text,
            "full_text":      full_text,
            "prompt_tokens":  prompt_tok,
            "gen_tokens":     gen_tok,
        }
        out_rows.append(row)
        cumulative_text_chunks.append(full_text)

    with args.output_jsonl.open("w", encoding="utf-8") as f:
        for r in out_rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    print(f"[gen] wrote {args.output_jsonl} ({len(out_rows)} rows)")

    if args.output_text:
        joined = "\n\n".join(cumulative_text_chunks)
        args.output_text.write_text(joined, encoding="utf-8")
        print(
            f"[gen] wrote {args.output_text} "
            f"({len(joined)} chars, ~{len(joined) // 4} tokens approx)"
        )


if __name__ == "__main__":
    main()
